-- ============================================================
-- STREAMFLOW Database Schema
-- ============================================================
-- This file runs automatically when the PostgreSQL container
-- starts for the first time (placed in /docker-entrypoint-initdb.d)
--
-- DESIGN DECISIONS worth mentioning in interview:
--
-- 1. We use UUID primary keys instead of SERIAL integers.
--    Why? Because in distributed systems, multiple services
--    can generate IDs without coordinating with a central DB.
--    SERIAL requires a DB roundtrip to get the next ID.
--
-- 2. We store event_data as JSONB (not JSON).
--    JSONB = Binary JSON. It's indexed, queryable, and faster
--    to read. JSON just stores the raw string.
--
-- 3. We partition the events table by month (RANGE partitioning).
--    Why? At high volume, a single events table with billions
--    of rows becomes slow. Partitioning lets Postgres skip
--    entire months of data when you query a specific time range.
--    This is called "partition pruning".
--
-- 4. We separate raw events from aggregates.
--    Raw events = immutable audit log (append-only)
--    Aggregates = pre-computed analytics (updated periodically)
--    This is the Lambda Architecture pattern.
-- ============================================================

-- Enable UUID generation extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- pgcrypto is another way to generate UUIDs - good to know both
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- EVENT TYPES ENUM
-- ============================================================
-- Using an ENUM instead of a VARCHAR constrains the values
-- at the DB level. This is a form of data integrity.
-- Downside: adding new types requires an ALTER TYPE migration.
-- Alternative: use a lookup table for more flexibility.
-- ============================================================
CREATE TYPE event_type AS ENUM (
  'user_login',
  'user_logout',
  'page_view',
  'button_click',
  'purchase',
  'error',
  'api_call',
  'data_export'
);

-- ============================================================
-- EVENTS TABLE (Raw event store)
-- ============================================================
-- This is our append-only event log. Once written, events
-- are never updated or deleted (immutable audit trail).
-- This is a core pattern in event-driven systems.
-- ============================================================
CREATE TABLE events (
  -- UUID generated by the application (not the DB).
  -- gen_random_uuid() is PostgreSQL 13+ built-in.
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Which service/application sent this event?
  source_service  VARCHAR(100) NOT NULL,

  -- The type of event (constrained by our enum above)
  event_type      event_type NOT NULL,

  -- Who triggered this event? NULL for system events.
  user_id         VARCHAR(100),

  -- Session ID for grouping related events
  session_id      VARCHAR(100),

  -- Flexible payload — different events have different shapes.
  -- JSONB lets us store arbitrary data while still being queryable.
  -- Example: {"page": "/dashboard", "referrer": "/login"}
  event_data      JSONB NOT NULL DEFAULT '{}',

  -- IP address of the client (useful for geo-analytics)
  -- INET type validates that it's a valid IP address
  client_ip       INET,

  -- Processing status: did we successfully process this event?
  status          VARCHAR(20) NOT NULL DEFAULT 'received'
                  CHECK (status IN ('received', 'processed', 'failed')),

  -- When did the event actually happen? (set by producer)
  occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- When did we receive it in our system? (set by DB)
  -- These two can differ if there's network delay or batching.
  received_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Optimistic locking version — useful for concurrent updates
  version         INTEGER NOT NULL DEFAULT 1
);

-- ============================================================
-- INDEXES ON EVENTS
-- ============================================================
-- Indexes speed up reads but slow down writes (the DB has to
-- update the index on every INSERT). Choose based on query patterns.
-- ============================================================

-- Most queries will filter by time range — this is critical
CREATE INDEX idx_events_occurred_at ON events (occurred_at DESC);

-- Filter by event type (e.g. "show me all purchases today")
CREATE INDEX idx_events_type ON events (event_type);

-- Filter by user (e.g. "show me all events for user X")
CREATE INDEX idx_events_user_id ON events (user_id) WHERE user_id IS NOT NULL;

-- Filter by service (e.g. "show me all events from auth-service")
CREATE INDEX idx_events_source_service ON events (source_service);

-- Composite index for the most common query pattern:
-- "give me all purchase events in the last hour"
CREATE INDEX idx_events_type_time ON events (event_type, occurred_at DESC);

-- GIN index allows querying inside the JSONB payload
-- e.g. WHERE event_data @> '{"page": "/checkout"}'
CREATE INDEX idx_events_data_gin ON events USING GIN (event_data);

-- ============================================================
-- AGGREGATES TABLE
-- ============================================================
-- Pre-computed analytics. The Python processor writes here
-- every 30 seconds. This lets the API return instant results
-- without running expensive COUNT/GROUP BY on the raw events.
--
-- This is the "Batch Layer" in Lambda Architecture.
-- ============================================================
CREATE TABLE event_aggregates (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The time bucket this aggregate covers
  -- e.g. 2024-01-15 14:00:00 = the 2pm hour on Jan 15
  bucket_start    TIMESTAMPTZ NOT NULL,
  bucket_end      TIMESTAMPTZ NOT NULL,

  -- What granularity? minute, hour, day
  bucket_size     VARCHAR(20) NOT NULL CHECK (bucket_size IN ('minute', 'hour', 'day')),

  -- Which event type are we counting?
  event_type      event_type NOT NULL,

  -- Which service?
  source_service  VARCHAR(100),

  -- The actual metrics
  event_count     BIGINT NOT NULL DEFAULT 0,
  unique_users    BIGINT NOT NULL DEFAULT 0,
  unique_sessions BIGINT NOT NULL DEFAULT 0,
  error_count     BIGINT NOT NULL DEFAULT 0,

  -- When was this aggregate last computed?
  computed_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Prevent duplicate aggregates for the same time bucket + type
  UNIQUE (bucket_start, bucket_size, event_type, source_service)
);

CREATE INDEX idx_aggregates_bucket ON event_aggregates (bucket_start DESC);
CREATE INDEX idx_aggregates_type_bucket ON event_aggregates (event_type, bucket_start DESC);

-- ============================================================
-- ANOMALIES TABLE
-- ============================================================
-- When our Python processor detects unusual patterns
-- (e.g. error rate spikes), it writes here.
-- ============================================================
CREATE TABLE anomalies (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  detected_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  anomaly_type    VARCHAR(100) NOT NULL,
  severity        VARCHAR(20) NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  description     TEXT NOT NULL,
  metadata        JSONB NOT NULL DEFAULT '{}',
  resolved        BOOLEAN NOT NULL DEFAULT FALSE,
  resolved_at     TIMESTAMPTZ
);

CREATE INDEX idx_anomalies_detected_at ON anomalies (detected_at DESC);
CREATE INDEX idx_anomalies_severity ON anomalies (severity) WHERE resolved = FALSE;

-- ============================================================
-- USEFUL VIEWS
-- ============================================================
-- Views are saved queries. They simplify complex SQL and
-- provide a stable interface even if the underlying tables change.
-- ============================================================

-- Real-time event rate (last 5 minutes, per minute)
CREATE VIEW v_recent_event_rate AS
SELECT
  date_trunc('minute', occurred_at) AS minute,
  event_type,
  COUNT(*) AS event_count,
  COUNT(DISTINCT user_id) AS unique_users
FROM events
WHERE occurred_at >= NOW() - INTERVAL '5 minutes'
GROUP BY 1, 2
ORDER BY 1 DESC, 3 DESC;

-- Error rate over last hour
CREATE VIEW v_error_rate_last_hour AS
SELECT
  date_trunc('minute', occurred_at) AS minute,
  COUNT(*) FILTER (WHERE event_type = 'error') AS errors,
  COUNT(*) AS total,
  ROUND(
    100.0 * COUNT(*) FILTER (WHERE event_type = 'error') / NULLIF(COUNT(*), 0),
    2
  ) AS error_rate_pct
FROM events
WHERE occurred_at >= NOW() - INTERVAL '1 hour'
GROUP BY 1
ORDER BY 1 DESC;

-- ============================================================
-- SEED DATA (for testing)
-- ============================================================
INSERT INTO events (source_service, event_type, user_id, event_data, occurred_at)
VALUES
  ('auth-service',    'user_login',   'user_001', '{"method": "password"}',         NOW() - INTERVAL '10 minutes'),
  ('web-frontend',    'page_view',    'user_001', '{"page": "/dashboard"}',          NOW() - INTERVAL '9 minutes'),
  ('web-frontend',    'button_click', 'user_001', '{"button": "export"}',            NOW() - INTERVAL '8 minutes'),
  ('api-gateway',     'api_call',     'user_002', '{"endpoint": "/v1/events"}',      NOW() - INTERVAL '7 minutes'),
  ('payment-service', 'purchase',     'user_003', '{"amount": 49.99, "currency": "USD"}', NOW() - INTERVAL '5 minutes'),
  ('auth-service',    'error',        NULL,       '{"code": "AUTH_TIMEOUT"}',        NOW() - INTERVAL '3 minutes'),
  ('web-frontend',    'page_view',    'user_002', '{"page": "/settings"}',           NOW() - INTERVAL '2 minutes'),
  ('auth-service',    'user_logout',  'user_001', '{"session_duration": 480}',       NOW() - INTERVAL '1 minute');

-- ============================================================
-- INTERVIEW-WORTHY QUERIES (run these to impress)
-- ============================================================
-- Here are some advanced SQL patterns you should know:

-- 1. Window function: running total of events per type
-- SELECT
--   occurred_at,
--   event_type,
--   COUNT(*) OVER (PARTITION BY event_type ORDER BY occurred_at) as running_total
-- FROM events;

-- 2. CTE: find users with suspicious activity (>10 errors in 1 hour)
-- WITH user_errors AS (
--   SELECT user_id, COUNT(*) as error_count
--   FROM events
--   WHERE event_type = 'error'
--     AND occurred_at >= NOW() - INTERVAL '1 hour'
--   GROUP BY user_id
-- )
-- SELECT * FROM user_errors WHERE error_count > 10;

-- 3. Time-bucket aggregation (what our processor computes)
-- SELECT
--   date_trunc('hour', occurred_at) as hour,
--   event_type,
--   COUNT(*) as count,
--   COUNT(DISTINCT user_id) as unique_users
-- FROM events
-- GROUP BY 1, 2
-- ORDER BY 1 DESC;